# Embeddings with PyTorch

author: __Pierre Nugues__

In [1]:
import torch
import torch.nn as nn


In [2]:
embedding = nn.Embedding(10, 3)
embedding


Embedding(10, 3)

In [3]:
embedding.weight


Parameter containing:
tensor([[ 1.5809,  0.2717,  0.4510],
        [ 0.1151, -1.3741, -0.0754],
        [-0.4393,  0.6695,  2.0121],
        [ 0.5194,  0.1159,  0.6411],
        [-0.6332, -0.4518, -0.2248],
        [ 0.6434, -1.9522, -0.5846],
        [ 0.8447, -0.7463, -0.9242],
        [-0.7032,  0.8451, -0.5661],
        [-0.4550,  0.6431, -1.3130],
        [-1.0583,  0.3888, -1.8614]], requires_grad=True)

In [4]:
input = torch.LongTensor([[1, 2, 4, 5], [4, 3, 2, 9]])
embedding(input)


tensor([[[ 0.1151, -1.3741, -0.0754],
         [-0.4393,  0.6695,  2.0121],
         [-0.6332, -0.4518, -0.2248],
         [ 0.6434, -1.9522, -0.5846]],

        [[-0.6332, -0.4518, -0.2248],
         [ 0.5194,  0.1159,  0.6411],
         [-0.4393,  0.6695,  2.0121],
         [-1.0583,  0.3888, -1.8614]]], grad_fn=<EmbeddingBackward0>)

The vector at padding index will not be updated, initially set to 0

In [5]:
embedding = nn.Embedding(10, 3, padding_idx=0)
embedding.weight


Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.8930, -0.7569,  0.2431],
        [ 0.3045,  0.0473,  0.7610],
        [ 2.0166,  0.5218, -0.9694],
        [ 1.0133,  0.6082,  0.8131],
        [-0.9300, -0.0680,  0.8860],
        [-0.8734,  0.0278,  1.3139],
        [ 0.0368,  1.2667,  1.1433],
        [-0.6458,  0.4116,  2.0016],
        [ 0.3347, -1.5406, -0.2118]], requires_grad=True)

In [6]:
input = torch.LongTensor([0, 2, 0, 5])
embedding(input)


tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.3045,  0.0473,  0.7610],
        [ 0.0000,  0.0000,  0.0000],
        [-0.9300, -0.0680,  0.8860]], grad_fn=<EmbeddingBackward0>)

Loading pretrained embeddings:

In [7]:
embedding_matrix = torch.FloatTensor([[1, 2, 3],
                                      [4, 5, 6],
                                      [7, 9, 9]])
embedding_matrix


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 9., 9.]])

In [8]:
embeddings = nn.Embedding.from_pretrained(
    embedding_matrix,
    freeze=False,
    padding_idx=0)
embeddings.weight


Parameter containing:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 9., 9.]], requires_grad=True)